### ISSUE TITLE
Maximum TIFF file size exceeded

### ISSUE THREAD

**Issue by ingrre** [Neural-Systems-at-UIO/nutil#145]
There are 17 files in one series that become invalid after running Nutil transform. N3 reports JAI error and Irfan View says:
": Decode error ! Invalid of unsupported TIF file".

Invalid files, s068 - s132, here: Y:\HBP-Voucher_Rat-corticome\SubProject2_PosterioParietalCortex\12906\rotate-rename-120820 (original TIFFs, s21 - s39, here: Y:\HBP-Voucher_Rat-corticome\SubProject2_PosterioParietalCortex\12906\2-TIFF\From_Dmitri)

Nutil reports "TIFFAppendToStrip: Maximum TIFF file size exceeded." (see attached screenshot). How would be the preferred way to go about to reduce the size of these images so that Nutil handles them? Original files are 2,5 - 3 GB.

![max-tiff-size](https://user-images.githubusercontent.com/38322594/90520992-4e05b000-e16a-11ea-9a8b-2258c4128537.png)

**Comment by Majpuc** [comment]
After discussion with Ingrid, it seems that these files are not originating from Nutil transform. Ask Dmitri.

**Comment by Majpuc** [comment]
@ingrre Is there any progress on this issue?

**Comment by ingrre** [comment]
No progress, haven't had the time to look at it again. Guess I will have to re-export. If you don't mind, it would be great if we could just keep the issue open until I'm done with pre-processing this series.

**Comment by ingrre** [comment]
Re-exported, tiled and reduced file size, and now it works. So we can close this issue for my part :)

**Comment by Majpuc** [comment]
Validated 06.01.2021 :)
