### ISSUE TITLE
Nutil resize of >5GB files

### ISSUE THREAD

**Issue by ingrre** [Neural-Systems-at-UIO/nutil#146]
The file is located here: Y:\HBP-Voucher_Rat-corticome\SubProject1_Orbitofrontal\Unfinished_data\New_sections\38-2 - F38_BDA_s061 (please note I did not produce this file myself and do not have the czi to reexport it).

Due to its large size, this file must  be resized. Running nutil transform of this file creates a 1kb file. Running nutil resize does not work, why? (no error message, but it says "no job loaded"). Is there a size limit for this functionality? 

Transcript from nutil:
"LOG: Type of operation: Resize"
"MESSAGE: Required memory: 0 GB. Free memory : 32647 GB from a total of 32647 GB installed (0 %) usage"
"LOG: Executing..."

**Comment by Majpuc** [comment]
Resize is working only on PNG and JPEG files (details in the manual). Do you know witch type of compression this file has ?
If it is originally from a Mirax file, we could try a New export...

**Comment by ingrre** [comment]
Aha, of course. No, don't have the original file. Would you know of a way to reduce size of tiffs? Tried Irfan view, but the program crashes

**Comment by ingrre** [comment]
Using x and y scale in transform works perfectly well - thanks!
