### ISSUE TITLE
Detect specific cells - request from NITRC

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#147]
Hi,

First, thank you for these amazing tools.
I have used both QhickNII and VisuAlign to get a great registration of my imaging stack to the mouse Allen CCF.
I then used Nutil to feed in a segmentation image (from Ilastik) and got the right results in terms of looking with the online MeshView
Attached is an example (slide1.png).

However I have a problem, I have other information relating to each one of these cells, and I want to know which one of the cells in the output report is which from the input.

Is there a way to know what is the order in which cells were detected?
Can I feed a label image which each cell having a different number to keep identity?

As I have already thresholded and trained a second Ilastik object based network I don't want to lose that information.
Any advice would be appreciated.

Thanks again,
Boaz

**Comment by sharoncy** [comment]
I carried this request over from the NITRC page for Nutil. It was reported on the 5th of July by Boaz Mohar.

**Comment by leuat** [comment]
Implemented a first version, will need some testing - (@sharoncy ) - like deciding which reports that should display the ID column etc

**Comment by sharoncy** [comment]
This has been tested and works fine. The object IDs are displayed in the last column in the object reports. In the image files, the region ID is printed above the object ID for each object. Help text has been added to the GUI.
