### ISSUE TITLE
Implement developmental mouse atlases in an embargoed version of Nutil

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#149]
Implement developmental mouse brain atlases in Nutil (P4, P14, P28, P56). The atlases are under embargo so should be implemented in a closed beta version of Nutil.

**Comment by sharoncy** [comment]
Instead of creating a closed beta version, we will implement support for custom reference atlases with a field for navigating to a label file.

**Comment by leuat** [comment]
Implemented!

**Comment by sharoncy** [comment]
I'm reopening this as I need to update the help text, plus test. But on first glace looks great.

**Comment by sharoncy** [comment]
I did a test with AMBA 2015 label file and this feature works great! Nutil generates empty customised reports with the customised atlas feature switched on unless a custom region file is provided. This should be described in the help text.

**Comment by sharoncy** [comment]
Help text implemented.
