### ISSUE TITLE
Quantifier - "Save as" - default directory should be last known location

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#155]
Ideally, the defalt directory that Nutil navigates to on pressing "browse" or "save as" should be the last known location, not some random place on the computer. At the moment, some of the buttons navigate to the last known location, other times it navigates to the Nutil software, etc, it's a bit random. For example, on pressing "Save as" one is always directed to the Nutil program folder.

**Comment by sharoncy** [comment]
I did some testing. All the "browse" buttons in Quantifier are fine. It's the "save as" that navigates to the wrong place.

**Comment by sharoncy** [comment]
This has been fixed internally (not yet published internally). The "save as" button now navigates to the last NUT file location. This feature needs to be tested.

**Comment by Majpuc** [comment]
Validated 09122020
