### ISSUE TITLE
Error message in Transform

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/nutil#157]
Would be great if Nutil would warn for untiled TIFFs also when 'only creating thumbnails'. Linked to issue#130

**Comment by sharoncy** [comment]
Done

**Comment by sharoncy** [comment]
I tested Transform with "only create thumbnails" and Nutil crashed with no error message. I am unsure if the input images were tiled or not tiled TIFFs. I assumed they were tiled, but it is possible they are untiled. (NOP dataset - see ilastik folder). @leuat We should look at this again.

**Comment by sharoncy** [comment]
The images are tiled with JPEG compression, with pink background colour. I applied autocropping, selected a pink colour that resembled the background colour, and applied a spread of 10. Nutil crashed. @leuat has been given a copy of the images so he can investigate the cause of the crash. Was it to do with the autocropping /background colour? Or something else to do with the images?

**Comment by sharoncy** [comment]
Close. 31.05.22.
