### ISSUE TITLE
Fails to create thumbnails if rotated images are big

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/nutil#162]
Nutil Transform fails to create thumbnails if the rotated images are above 4 GB. The big rotated images are produced normally. No error message is displayed.
Both original images and storage are local (external hard drive), Nutil was also operated locally.

**Comment by sharoncy** [comment]
The big rotated images are above the upper size limit for tiled TIFFS (4 GB) and so are corrupted. This is why Nutil fails to produce thumbnails. I have updated the user manual and the help text in the Nutil GUI with this info.

**Comment by Majpuc** [comment]
This issue will be solved by implementing BigTiff support. New card will be created about this. 06.04.2021
