### ISSUE TITLE
Transform - "From Excel" 

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#163]
The "From Excel" button imports parameters from an excel sheet. This button does not work if there is already data in the Transform GUI. One has to press "clear" first and then "from excel". This is not intuitive.

**Comment by sharoncy** [comment]
A message has been added to inform users that the data from excel is added to the list. It does not overwrite the data but adds it. To overwrite, you first press "clear" and then "from excel".

**Comment by Majpuc** [comment]
Validated 09122020
