### ISSUE TITLE
Mask help for brain hemisphere distinction 

### ISSUE THREAD

**Issue by mcgeedev** [Neural-Systems-at-UIO/nutil#164]
In Nutil I want to differentiate between staining in my Brain's hemispheres.  I see that you give an option for Masks in the manual, Is masking the only way to do this?  Currently we have many brains that we want to put into this workflow but creating an individual mask that divides each individual brain at the correct angle seems like a big bottleneck for the workflow.  I ended up making my mask in paint, but don't know if this is ideal or another user here has found a quicker way to do this for each brain?  Am I perhaps missing another way that I can address this hemisphere distinction that doesn't require mask creation for each individual section before getting my analysis done?

Thanks so much for all your work!

**Comment by sharoncy** [comment]
@mcgeedev Thanks for your question, it's always nice to hear from users. I will look into options for you and get back ASAP. Sharon

**Comment by sharoncy** [comment]
@mcgeedev We have a standalone tool called QuickMask that can be used to automatically generate hemisphere masks for a whole series of images based on the QuickNII file. If you email me at s.c.yates@medisin.uio.no I can send it to you with some simple instructions. The software is currently a Windows application. Let us know if you need a version for Mac or Linux.

**Comment by mcgeedev** [comment]
Wow that sounds great!  Thanks so much I will not need a Mac or Linux version and i will email you now
