### ISSUE TITLE
Region label output

### ISSUE THREAD

**Issue by mcgeedev** [Neural-Systems-at-UIO/nutil#166]
Hello,

I had a question about labels that get output and I was wondering if this is the correct forum for it, or maybe there is a place on image.sc for this?  If so I'm happy to delete and repost there!

<img width="808" alt="clear label" src="https://user-images.githubusercontent.com/73913367/99691868-ad1fdd00-2a57-11eb-8547-01433410d274.PNG">

What does clear label mean when there is a region that is 0 (aka theoretically doesn't exist) but there is a detection of staining?

Thanks!

**Comment by mcgeedev** [comment]
I found my answer in the user guide - i must have missed it in my first read through- thanks!

**Comment by sharoncy** [comment]
@mcgeedev Great that you found the answer. This is the right place to post issues and questions. We are always grateful for feedback, questions and requests, so feel free to ask more if there is anything.
