### ISSUE TITLE
Compilation Guide

### ISSUE THREAD

**Issue by GxHam** [Neural-Systems-at-UIO/nutil#169]
Hi,

The nitrc server seems to be down hence I am unable to download the executable. I am new to C++, and hence have no idea how to go about compiling the code from source. Would it be possible to include a guide for compiling nutil from scratch?

**Comment by sharoncy** [comment]
Hi,
The nitrc server is up again, I managed to download Nutil this morning, but let us know if you still have problems. We are releasing v405 of Nutil very soon - hopefully in the next week or so- with some usability improvements, small bug fixes, help text updates, updated user manual, etc, so good idea to download that one when it's out.

**Comment by GxHam** [comment]
Hi Sharon,

Thank you so much for testing it out. I realized the issue was with my internet service provider. The website worked after I switched the connection to my mobile hotspot.

Though it would still be nice to have a short installation tutorial for building from git, to be connected to the dev versions :)

Thank you once again!

**Comment by leuat** [comment]
@GxHam Hi there! I've updated Nutil's main github page (the readme.md) to include a set of instruction on how to compile from scratch. Let me know if you have any problems!
