### ISSUE TITLE
Nutilv405 Crash

### ISSUE THREAD

**Issue by briannnagurdon** [Neural-Systems-at-UIO/nutil#172]
When creating a new Qualifier file Nutil frequently crashes once I get down to adjusting the advanced settings. This does not happen when changing a particular drop-down option but instead can occur when I go to change any of the later settings. It doesn't seem like there is a pattern as to when it crashes. In the instances this does occur the program buffers/loads for a couple of seconds and then closes out of the GUI and CMD line prohibiting me from creating the files or running the series.

**Comment by sharoncy** [comment]
This problem applies to v405_temp. I replicated the crash by filling in all the Quantifier fields from scratch. Nutil crashed when i tried to move the scroll bar to navigate down the form (I got as far as mask info, then tried to scroll down). I got the error message: "Nutil has stopped working" with no additional info.

**Comment by sharoncy** [comment]
I tried it a second time and Nutil did not crash. Quantifier ran successfully. On the third test, I again replicated the crash. It happened when I tried to scroll down, this time at a different place in the form (I got to customised reports). I suspect the crashing problem is related to the scroll bar.

**Comment by sharoncy** [comment]
I did a test of the latest version of Nutil in Qt. Tried with the same dataset as above. This time Nutil crashed when I tried to switch between options for one of the advanced settings. Nutil froze then closed itself down with no error message.

**Comment by sharoncy** [comment]
This has been fixed and Nutil v0.407 released on NITRC. Please report back if you continue to have problems.
