### ISSUE TITLE
Option to browse for folders housing masks 

### ISSUE THREAD

**Issue by briannnagurdon** [Neural-Systems-at-UIO/nutil#173]
Is it possible to adjust Nutil to make it look for masks in a separate folder instead of having the images in the same folder as the segmented images? For example, since the masks are made on a brain-wide basis including the multiple stains used, currently you would have to drag all the appropriate masks into their stain specific segmentations folders, but if the masks feature had the same browse function as the other segmentation or brain atlas maps features it would be much more efficient to just be able select that one folder for the brain and all stains.

**Comment by sharoncy** [comment]
I agree that this would be useful for all users.

**Comment by sharoncy** [comment]
This has been implemented but need to update the help text. The mask feature now works with either masks in the segmentation folder or in the specified directory.

**Comment by sharoncy** [comment]
Released in v0.407.
