### ISSUE TITLE
Nutilv404 crashes while running the quantifier

### ISSUE THREAD

**Issue by namercer** [Neural-Systems-at-UIO/nutil#174]
Nutil is crashing when running the quantifier after loading the ventricular systems without listing a specific error. All images are stored locally and Nutil is run locally.

![IMG-6847](https://user-images.githubusercontent.com/4682140/103683932-aa157900-4f3f-11eb-9af8-853a9d1a84aa.jpg)

**Comment by Majpuc** [comment]
Thank you for notifying the error. We are working on it.

**Comment by sharoncy** [comment]
We found a big bug in Nutil, which has now been fixed. You can download the updated version at https://www.nitrc.org/projects/nutil/ (version 0.407). Hopefully this will fix your crashing problem. If not, please get back to us and we will look into it in more depth! And thank you for reporting this problem.

**Comment by namercer** [comment]
Thanks for looking into this! The updated version still crashes when I try to run as before. I tried to start a new project to see if it was the details of those images and files that were the problem but now when I try to use the tiffcreator it creates empty/corrupted files that the transformer identifies as corrupt. The original image files are tiled .czi files that I convert to .tiff in fiji before running them in the tiffcreator. I have tried running Nutil on two different computers (windows 10) with the same result so maybe the problem is the original images? 
Thanks again for your help!
![Screenshot 2021-01-10 153908](https://user-images.githubusercontent.com/4682140/104138621-0de1dc80-535a-11eb-9015-54bc51ab3018.png)

**Comment by leuat** [comment]
Could you send me a zip file with your nutil setup containing 1 of these images that fail? (i.e. copy your directory to a new one, delete most of the image files, zip down) and send to leuat@irio.co.uk!

**Comment by sharoncy** [comment]
Thanks for reporting this error. We have investigated and found a number of problems with your input files: 1. Your XML file was empty. This is why Nutil crashed. It should contain anchoring information, this is generated with QuickNII. Make sure to save the XML or JSON file once you have finish anchoring with QuickNII and point to this file in Nutil (the XML and JSON files contain the same info and are both compatible with the latest version of nutil).  2. Your segmentations were black, they didn't have the glasbey lookup table applied. See the ilastik user manual that is part of the Nutil package for instructions on how to apply this. By doing this, the objectsare assigned a colour (for example, red), and then you select this colour to extract with Nutil. @leuat Was there anything else? @namercer Please let us know if you still have problems and we will investigate further.

**Comment by sharoncy** [comment]
We will add an error message to the next version of Nutil so that Nutil doesn't crash with empty XML files, but instead displays an error message. So thank you for this feedback.

**Comment by RPorneso** [comment]
Hi @sharoncy,

I read this trail and made sure I have version 0.407, my xml file has the coordinates and that all my segmentation images are converted to glasbey png files but i still get the same error as what' s described here by other users.  Can someone help? I am sending a sample segmentation file to @leuat along with a sample anchored slice to CCFV3 and my xml file.
![Screenshot 2021-02-01 at 17 26 21](https://user-images.githubusercontent.com/68513135/106490057-b5fc4880-64b5-11eb-84f9-d4e0912cd014.png)

**Comment by sharoncy** [comment]
I did a quick test with the most up-to-date version of Nutil (not yet released on NITRC), and I got the following error message: ![Ralph_error](https://user-images.githubusercontent.com/30626642/106582646-83e5f780-6544-11eb-948e-6d57c3553c25.PNG). So it looks like there is something with the XML file. @Majpuc will look into this further and get back to you. Thanks for reporting!

**Comment by RPorneso** [comment]
Thanks for the quick response! Does this error message only appear at slice 253, so almost at the end, or does it occur much earlier? I can check if i did something funky with the renaming of my files from slice 253, if so. Looking forward to your feedback. Much appreciated!!

**Comment by sharoncy** [comment]
I think the error occurs for earlier slices too. I suspect some of the sections haven't been anchored so that the XML file doesn't contain all the info required, but we will investigate more here today and get back to you.

**Comment by sharoncy** [comment]
We discovered a bug in Nutil: there was an unintended upper size limit for the segmentations causing the Nutil crashes with large segmentation sizes. The size limit has been removed and will be released in version 0.408.

**Comment by RPorneso** [comment]
Thanks! Do you have a timeline when v0.408 will be released?

**Comment by sharoncy** [comment]
I sent you a temporary version of Nutil v0.408 via filesender today. Please test it out and let us know if it works.

**Comment by sharoncy** [comment]
@namercer @RPorneso We discovered two bugs affecting the Quantifier reports in several older versions of Nutil: 
Bug 1: 	Load output in the slice reports are incorrect for Nutil v0.4.0 – v0.5.0. The other results in the reports are correct. 
Bug 2: 	When using the mask feature: region pixels, region areas and loads in the reports are incorrect for Nutil v0.4.3 – v0.5.0. This bug does not affect analyses run without masks. 

The bugs are now fixed in Nutil v0.6.0 (stable), which is released on NITRC.org. As the bugs affected core Quantifier functionality, we have introduced more stringent quality assurance routines, with continuous integration (CI) and automatic validation based on an expanded collection of ground truth datasets. We will provide more information about this in a future Nutil release. Until then, please delete all affected analyses and rerun with the new version of Nutil. We are sorry for not picking up on this sooner! If you have questions, don't hesitate to contact me at s.c.yates@medisin.uio.no.
