### ISSUE TITLE
Nutil crash v407

### ISSUE THREAD

**Issue by mcgeedev** [Neural-Systems-at-UIO/nutil#176]
Hello,
I am getting a crash in nutil when I attempt to run batch of images, message that appeared is below (pulled from nutil_log) and then the program closes are does not produce any  output files 

LOG: Type of operation: Quantifier
MESSAGE: Found report: <font color="#ff0000">Cortex</font> ( 389 ids )
MESSAGE: Found report: <font color="#ff00ff">Fibretracts</font> ( 191 ids )
MESSAGE: Found report: <font color="#ffff00">Hippo</font> ( 100 ids )
MESSAGE: Found report: <font color="#0000ff">Olfactory</font> ( 75 ids )
MESSAGE: Found report: <font color="#00ff00">Hypothalamus</font> ( 85 ids )
MESSAGE: Found report: <font color="#000000">Striatum_Pallidum</font> ( 68 ids )
MESSAGE: Found report: <font color="#ffacfd">Mid_Hind_Medulla</font> ( 187 ids )
MESSAGE: Found report: <font color="#fe8f42">Thalamus</font> ( 70 ids )
MESSAGE: Found report: <font color="#ffffff">Cerebellum</font> ( 86 ids )
MESSAGE: Found report: <font color="#98fb98">VentricularSystem</font> ( 34 ids )

Also another question I had was my segmentations aren't lining up with my non-linear atlas - the aspect ratio of the visualign and quickNII outputs are different from my original photos and from my segmentations.  Did i miss something as to why that ratio would change?  the output produces this photo --> where the positive marks should be in the light green
![numbers should be in light green](https://user-images.githubusercontent.com/73913367/104231141-7ee9c880-541c-11eb-8602-23b771dd828b.png)

As always, thank you for your help and work!

**Comment by leuat** [comment]
Hi there! Could you send me a copy of the project (NUT files + anchor + segmentation data etc)? leuat@irio.co.uk

**Comment by Majpuc** [comment]
Hi Mcgeedev! Sorry the hear about your issues with Nutil. In order for us to investigate could you send a zipped folder containing a copy of the .nut file you used when it crashed as well as one original image, the corresponding atlas map, corresponding segmentation image and corresponding output (atlas+ objects). Please send these to us.
It also seems that you have a discrepancy in the images proportions. Segmentation images must have the same proportions as the images used to generate the atlas maps. They do not need to be of the same size. Depending on the size of your objects to segment, the source images need to be resized before use. Maybe one set for QNII/VisuAlign registration (as there is a size limit of ) and one set with higher resolution for ilastik segmentation. But the XY proportions should remain the same.

**Comment by mcgeedev** [comment]
Yeah, I will get that email to you all today - thank you!   As for the image proportions when playing around with it today I noticed that my original image and segmentation image are the same size/same proportions but when taking my 1st image into QNII to register it the program spits out a file that already ruins the proportions.  Say my original image is 1.318 width/height the corresponding file from QNII is 1.455 width/height.

**Comment by Majpuc** [comment]
Hi, could you elaborate on that? QuickNII file builder will create and xml file from your png or jpeg files (wich one do you have?) but does not alter the size of the files. So the number of pixels in X and Y are not changed. After registration is completed, you can export atlas maps. These atlas maps should have the same proportions as the input images. Rounding up the numbers of pixels could give a tiny difference but should not create such a mismatch as you report here. Could you send to me sample images? majapu@uio.no Thanks!

**Comment by mcgeedev** [comment]
My exported atlas map images dont have the same proportions as my segmentation and original images for some reason!

I sent all emails mentioned above - thanks all!

**Comment by mcgeedev** [comment]
Hey all,

I have an update - it looks like I used the wrong anchor file on accident when running the program and when I corrected this the program didn't crash.  I originally selected my quickNII XML file instead of the JSON.   I was able to replicate the crash by rechoosing my XML file from quickNII where Total[ ] returns NaN and then the program closes without any feedback.  When I open the program and chose the JSON file from quickNII there is no crash AND I get results

> Wed Jan 13 10:10:47 2021 : Found report: Cortex ( 389 ids )
> Wed Jan 13 10:10:47 2021 : Found report: Fibretracts ( 191 ids )
> Wed Jan 13 10:10:47 2021 : Found report: Hippo ( 100 ids )
> Wed Jan 13 10:10:47 2021 : Found report: Olfactory ( 75 ids )
> Wed Jan 13 10:10:47 2021 : Found report: Hypothalamus ( 85 ids )
> Wed Jan 13 10:10:47 2021 : Found report: Striatum_Pallidum ( 68 ids )
> Wed Jan 13 10:10:47 2021 : Found report: Mid_Hind_Medulla ( 187 ids )
> Wed Jan 13 10:10:47 2021 : Found report: Thalamus ( 70 ids )
> Wed Jan 13 10:10:47 2021 : Found report: Cerebellum ( 86 ids )
> Wed Jan 13 10:10:47 2021 : Found report: VentricularSystem ( 34 ids )
> Wed Jan 13 10:10:47 2021 : Required memory: 0.339775 GB. Free memory : 16190 GB from a total of 16190 GB installed (0 %) usage
> Wed Jan 13 10:10:56 2021 : ****** Count of pixels 58378
> Wed Jan 13 10:10:56 2021 : WARNING: Some of the area matrices were not initialized. Please make sure that you are using a correct anchor xml file!
> Wed Jan 13 10:10:56 2021 : ****** Count of pixels 58378

Is the message returned 

In addition, this run of files returns output images that are much much better and look like they are very close to the correct place for staining I haven't examined them nor the excel output really closely yet though 

Thank you for the help and patience !

**Comment by Majpuc** [comment]
Issue resolved 19.01.2021

**Comment by sharoncy** [comment]
@mcgeedev 
We discovered two bugs affecting the Quantifier reports in several older versions of Nutil: 
Bug 1: 	Load output in the slice reports are incorrect for Nutil v0.4.0 – v0.5.0. The other results in the reports are correct. 
Bug 2: 	When using the mask feature: region pixels, region areas and loads in the reports are incorrect for Nutil v0.4.3 – v0.5.0. This bug does not affect analyses run without masks. 

The bugs are now fixed in Nutil v0.6.0 (stable), which is released on NITRC.org. As the bugs affected core Quantifier functionality, we have introduced more stringent quality assurance routines, with continuous integration (CI) and automatic validation based on an expanded collection of ground truth datasets. We will provide more information about this in a future Nutil release. Until then, please delete all affected analyses and rerun with the new version of Nutil. We are sorry for not picking up on this sooner! If you have questions, don't hesitate to contact me at s.c.yates@medisin.uio.no.
