### ISSUE TITLE
Error in Running Nutil from Command Line

### ISSUE THREAD

**Issue by briannnagurdon** [Neural-Systems-at-UIO/nutil#178]
I am able to run individual .nut files from the GUI from both the Nutil Window Command Script and from the nutil_program.exe in the program file; however, when I try to batch process the .nut files in the command line as I have with previous Nutil versions I receive the error seen in the screenshot. 
![CMDlineError](https://user-images.githubusercontent.com/76436445/105859869-fee66580-5fba-11eb-8d1e-8b90d46819c5.jpg)

**Comment by Majpuc** [comment]
Mistake from the user. Closed 29.01.2021
