### ISSUE TITLE
Maximum Object Size Error

### ISSUE THREAD

**Issue by briannnagurdon** [Neural-Systems-at-UIO/nutil#179]
In an attempt to check that my objects were not larger than the max object size I set, I received an error of "Error: max pixel cutoff cannot be lower than lower pixel cutoff" when the min value is set to 1 and the max value is set to 10,000,000,000. This error does not impact my specific quantification, just something I ran across when testing the limits.

**Comment by sharoncy** [comment]
It was decided to remove the max cutoff feature from nutil. This was implemented in v0.5.3.

**Comment by sharoncy** [comment]
Validated 02.03.21.
