### ISSUE TITLE
Instructions / procedure description for preparing AxioScan images for use with image registration tool

### ISSUE THREAD

**Issue by leergaar** [Neural-Systems-at-UIO/nutil#192]
An internal technician needs to process AxioScan images (CZI or exported TIFFs) before upload to image management system (full resolution) and extraction of small images for use with QuickNII. Processing steps will include basic operations such as image rotation, mirroring, and renaming. Is there a tutorial / procedure description available, or is it easier with direct instructions?

**Comment by Majpuc** [comment]
Export of tiled Tiffs from CZI files is described in Nesys internal documents  OP_001D_v1 and OP_001E_v1.
Preprocessing of tiled Tiff images to desired format and size can be achieved with Nutil Transform. The Nutil manual is found in the downloaded installation folder. https://www.nitrc.org/projects/nutil
