### ISSUE TITLE
Adapt z-spread script to fit .json files from Nutil

### ISSUE THREAD

**Issue by marovst** [Neural-Systems-at-UIO/nutil#198]
The current Z-spread script spreads coordinates perpendicularly along an axis with user-defined Gaussean spread. This works fine for spreading coordinates in .txt files, with point-coordinates extracted from LocaliZoom. The files are very large, which makes it difficult to do the process manually. We now need a customized script that works with .json output files from Nutil. We have 200+ nutil files with a large number of points that need z-spread. 

Current script + .json file from Nutil (for testing):
[OldScript_and_TestCoordinates.zip](https://github.com/Neural-Systems-at-UIO/nutil/files/6285426/OldScript_and_TestCoordinates.zip)

**Comment by sharoncy** [comment]
Adding to the to do list, and assigning to you @leuat

**Comment by Majpuc** [comment]
Any news here? @leuat

**Comment by leuat** [comment]
@marovst see if this one works. Should also support colours from the .json file
[spread.py.zip](https://github.com/Neural-Systems-at-UIO/nutil/files/6569159/spread.py.zip)

**Comment by sharoncy** [comment]
Martin has tested the script and it works. However, he is not able to open the coordinate files with meshview as they are too big. As a workaround he is excluding some regions from the files. He will test this out some more and get back to us if script changes are needed. We will close this issue by the end of the week @marovst unless we hear anything more.

**Comment by leuat** [comment]
[spread.py.zip](https://github.com/Neural-Systems-at-UIO/nutil/files/6576326/spread.py.zip)
@marovst this one outputs .json files + colours. Let me know if the spreading works!
