### ISSUE TITLE
Similar issue to #174 

### ISSUE THREAD

**Issue by digitizemecaptain** [Neural-Systems-at-UIO/nutil#200]
Hi,

Thanks for developing this software. I have a similar issue to ISsue #174. Whether I run my dataset or the dataset you provide in validation (either G2 or G3), I get the same problem where it doesn't proceed past Ventricular system. Any suggestions would be really appreciated.
<img width="677" alt="Screenshot 2021-04-13 103252" src="https://user-images.githubusercontent.com/82458914/114570200-a3378a00-9c43-11eb-8a6b-237bed8368ac.png">

Thanks,
Dan

**Comment by Majpuc** [comment]
Hi, thank you for contacting us. This issue was occurring in version v0.4.0. and should be fixed in the stable version v0.6.0. Which Nutil version did you use?

**Comment by digitizemecaptain** [comment]
Thanks for getting back so quickly, I re-downloaded and got one step further before crashing. I'm not exactly sure why but when I fixed my naming nomenclature to the standard "_sXXX" then everything just worked. Problem solved!
