### ISSUE TITLE
Nutil output do not count all the target regions 

### ISSUE THREAD

**Issue by marovst** [Neural-Systems-at-UIO/nutil#202]
In a few of my nutil analyses the output does not included all my target regions. It should be noted that I have used custom regions with the thalamus, cortex, caudoputamen, superior colliculus and pontine nuclei active. These analyses have been done with an old version of Nutil, however, I have rerun the affected cases with the newest version with no change in output.  

In the problem cases the output images have affected brain regions of a different color (see attached images). 

Can you help me find out why this happens? I need these inputs to my analyses. 

Link to an example case where this issue happens:
Z:\HBP_Analytics\Nutil_Connectivity\PhD_Martin\Allen_connectivity\Allen_connectivity_126908007_SSp_n
Image with an example for the case 126908007_SSp_n showing input at left and output at right. Note the change in color in the output image compared to the input image
![StrangeOutput](https://user-images.githubusercontent.com/34418916/116556776-1dcbff00-a8fe-11eb-8564-59c14cb5b3ff.jpg)

Input and output for another case with no problems: 
Z:\HBP_Analytics\Nutil_Connectivity\PhD_Martin\Allen_connectivity\Allen_connectivity_117298988_SSs
![StrangeOutput_2](https://user-images.githubusercontent.com/34418916/116557867-28d35f00-a8ff-11eb-873a-c78944aa9ab9.jpg)

**Comment by sharoncy** [comment]
Hey @marovst. @leuat  and I had a look this morning but we need more info to figure this out. Can you point out exactly what is wrong in the example above (an example slice report that does not include a region that should have been included, please be very specific). I ran the analysis and at first glance it looks fine. Also, if you haven't done it already, please make sure the custom region.xlsx has the correct IDs listed per region, that it corresponds to AMBA v2017, etc.

**Comment by sharoncy** [comment]
The atlas maps for the series that haven't worked here are generated based on the 2015 version of AMBA. I have tested Quantifier with AMBA 2015 for these files and they produce correct results. There is currently no way to check the atlas version by looking at the atlas maps themselves so I will raise this issue with @Tevemadar as it's a repeating problem and makes it difficult to problem solve.

**Comment by sharoncy** [comment]
Let us know if you still have problems @marovst . If I don't hear anything in a few days I'll close this issue.

**Comment by Majpuc** [comment]
Issue closed 11.05.2021
