### ISSUE TITLE
Have to shut down and reopen Nutil to get it to work

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#203]
On my new laptop I have to open Nutil, shut it down and reopen it to get it to actually process a dataset with Quantifier. The first time round it looks like everything is fine, I can fill in the template in the GUI, etc, but nothing happens when I press "start". Not sure if this happens to other users too, is it something you've experienced @Majpuc ?

**Comment by sharoncy** [comment]
Another related issue is that Nutil shuts itself down after finishing an analysis so that it looks like it's crashed but it hasn't really. The older versions didn't do this.

**Comment by Majpuc** [comment]
I've experienced this once but didn't recur later on.

**Comment by sharoncy** [comment]
Martin also experiences this today (he said it said "no job loaded"). It's a repeating problem with the latest version that users have to open and shut down and reopen to get it to recognise Nut files. Any ideas @leuat ?

**Comment by Majpuc** [comment]
After Quantifier analysis with WHSv3, Nutil crashes and exit either after reports not making the coordinate files or after making coordinate files if no report was selected. No error message.

**Comment by sharoncy** [comment]
This issue hasn't been reported recently. close 19.01.22
