### ISSUE TITLE
Quantifier Images

### ISSUE THREAD

**Issue by GxHam** [Neural-Systems-at-UIO/nutil#205]
Hi,

Would it be possible to output the images from the quantifier as meshes instead of against a colored atlas?

**Comment by Majpuc** [comment]
Hi GxHam,
The coordinate file for the 3D objects allow you to visualize your objects in 3D. In a sw like MeshView you will be able to visualize the atlas meshes as well. https://www.nesys.uio.no/MeshView/meshview.html?atlas=ABA_mouse_v3_2017_full

**Comment by GxHam** [comment]
Hi Majpuc,

How would I trigger the mesh view in the link provided? I can only adjust the transparency of the regions, but it is still colored. I'd like mesh view similar to in VisuAlign when you drag the cursor all the way to the right side. I'm quantifying fibers, hence it is quite difficult seeing the points past the colored background.

**Comment by GxHam** [comment]
Alternatively, would it be possible to export the images without the numbers but with the cloud points only? Here is an example.
![003_stitched_FFC_VV33-01_s02_AF568](https://user-images.githubusercontent.com/53009065/117388048-8f1e3a00-af1c-11eb-8cb3-2f1a5bfa1822.png)
Can I remove the mini numbers somehow?

**Comment by Majpuc** [comment]
Hi GxHam, regarding your question: in MeshView you cannot see the outline only as you can in VisuAlign. The high number of atlas regions makes the visualization a bit difficult in 3D. Even having outline only would be very crowded. Using this link https://www.nesys.uio.no/MeshView/meshview.html?atlas=ABA_mouse_v3_root  you will be able to look at a transparent brain and then can activate or deactivate the region meshes as your convenience.
![image](https://user-images.githubusercontent.com/46992863/117430817-c8f53d80-af28-11eb-81c1-12e846b0a9d9.png)

**Comment by GxHam** [comment]
Hi @sharoncy - Thanks for the advice! I managed to generate the image files without region ID :)
Hi Majpuc - only showing root does make visualization better :) thank you so much!

However I was wondering if this is normal? 
![image](https://user-images.githubusercontent.com/53009065/117633104-4b436300-b1b0-11eb-8709-3d8b7be539c3.png)
It is taking me super long to generate the cloud points even when I set the cloud point density to 1000000. If you have any advice on visualizing fibers I'm all ears as well :)

**Comment by GxHam** [comment]
Hi Majpuc, thank you so much for the advice. I'll try it out and see if things improve. Another issue I noticed was that when using the Mask feature to isolate hemispheres, I sometimes run into issues where the quantification gets stuck for a few slices, and I get a barrage of error messages. I've attached the corresponding images below:
![image](https://user-images.githubusercontent.com/53009065/117919349-6c769180-b31f-11eb-9ff3-bce84d137ae6.png)
![image](https://user-images.githubusercontent.com/53009065/117919373-74cecc80-b31f-11eb-9f0e-d00e0b713e79.png)
This happens occasionally, and I can get through the quantification if I restart nutil and run it again. But I wonder if there is a bug in the program.

**Comment by Majpuc** [comment]
Dear GxHam, Thanks for reporting this. We will have a look at it as soon as possible.

**Comment by sharoncy** [comment]
@GxHam. I'm not sure what is happening here. I'd need an example dataset to be able to investigate further. If you're happy to share please email me a zipped folder with all the input files required for an analysis that failed and I'll look into it when I have some time. s.c.yates@medisin.uio.no

**Comment by sharoncy** [comment]
I haven't received a response here. @GxHam Maybe this resolved itself? I will close this issue soon unless I hear otherwise.
