### ISSUE TITLE
Follow Up on masking (#164) in Nutil 

### ISSUE THREAD

**Issue by noahlubben** [Neural-Systems-at-UIO/nutil#208]
Hello. I am following up on a past lab member's question as it has been some time. We are returning to Nutil to differentiate hemispheres of our stained sections.

I know previously the tool QuickMask was suggested. Is this tool available and functional or since the previous discussion is there another way to achieve this? 

Appreciate all your work!

**Comment by sharoncy** [comment]
Hi. Yes, QMask generates black/white masks to enable differentiation of hemispheres based on a QuickNII XML file containing registration information for the series. If you email me I'll send you a copy with a user manual: s.c.yates@medisin.uio.no.

**Comment by sharoncy** [comment]
I have sent the files by email.

**Comment by noahlubben** [comment]
Hello sharoncy, 

Thank you so much sharing the file and the manual with us! I am happy to report the Qmask Tool works exactly as it should for our purposes of hemispheric differentiation. Thank you so much for your help and all your work!

**Comment by sharoncy** [comment]
Great to hear that it works. This issue is now closed 10.06.21.
