### ISSUE TITLE
Nutil support for viewer formats, e.g. neuroglancer precomputed chunks

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#212]
The ilastik team do not currently plan to support output formats other than those supported by the relevant viewer (e.g. neuroglancer precomputed chunks or DeepZoom). This will require Nutil support for whichever file format applies. This is not particularly user friendly as it will not enable download of the segmentations by users.

Suggestions: 
1. Implement Nutil support for the viewer formats. For the purpose of the demo, it may be necessary to implement support for the neuroglancer precomputed chunks (find more info about this on the "useful info" page on the QUINT developers collab). 
2. Implement Nutil support to convert these N3 files to more standard formats that can be downloaded by the user (for example, PNG).

**Comment by Majpuc** [comment]
No longer relevant. Other solution was developed in PyNutil
