### ISSUE TITLE
Wrong rat brain area labelling after running the QUINT-workflow with the WHSRat-v3-atlas

### ISSUE THREAD

**Issue by Wissewald** [Neural-Systems-at-UIO/nutil#214]
I was trying to test run the QUINT-workflow with Ilastik-segmentation of a confocal image and a brightfield image (of the same slice) registered in the WHSRat-v3-atlas.
The problem is that the brain areas are wrongly labelled; e. g. "corpus callosum and associated subcortical white matter" is labelled as "olfactory bulb", "neocortex" as "pyramidal decussation" and "hypothalamic region" as "brainstem".

I would be gratefull for any advice. 
Thanks in advance!

Wissewald

![MATLAB_plot+QuickNII_segmentation](https://user-images.githubusercontent.com/86107186/122577225-d38c1200-d052-11eb-85f3-50abcdba2a18.png)

**Comment by leuat** [comment]
Are you certain that you've used the correct WHSRat atlas version (2015 etc) when a) using quicknii and b) using nutil? If not, then labels will typically be completely incorrect, as the ID values are different for the different atlases

**Comment by Wissewald** [comment]
Yes, I'm sure I used the same atlas in QuickNII and Nutil.
What may have caused the problem is that I used an overlay of 2 Ilastik-segmentations and specified the object color as the color of the overlay. But after rerunning Nutil with an 8-bit-png-file of a simple segmentation in Ilastik (no overlay, just black objects on white background) resulted in the same wrong labelling.

**Comment by Wissewald** [comment]
I tried non-linear registration in VisuAlign with the xml-file from QuickNII and then used the resulting json-file for Nutil Quantifier. It worked, as you can see, the areas are labelled correctly and also the colors match with the WHSRat-v3-atlas.

![untitled](https://user-images.githubusercontent.com/86107186/126357968-e1896cd5-a04f-4a6f-8f02-51c95ff42823.png)

**Comment by Majpuc** [comment]
Hi,
This is very helpful! thanks! We might have a bug in the QuickNII version of WHSv3 then. We will look into this!

**Comment by sharoncy** [comment]
@Wissewald Would you be able to send an atlas map, a matching segmentation, the XML and the Nut file for the first erroneous analysis to s.c.yates@medisin.uio.no please? I'd like to investigate. 

Did the second analysis you did resolve your issue, or is it important for you to get it to work without VisuAlign? I will investigate either way, just wondering where you are in terms of your analysis. 

Thanks!

**Comment by sharoncy** [comment]
Wissewald sent me some files and I tested. I didn't manage to duplicate the error, the analysis worked as it should including the coordinate extraction, so I don't think there is a bug here. I did update some settings in his NUT file. 
He is happy with this now so I will close this issue. 
Sharon Yates 28.07.21.

**Comment by sharoncy** [comment]
Validated 25.08.21.
