### ISSUE TITLE
Unexisting objects detected at the edge of the image

### ISSUE THREAD

**Issue by Wissewald** [Neural-Systems-at-UIO/nutil#216]
As you can see [here](https://github.com/Neural-Systems-at-UIO/nutil/issues/214), some objects were detected at the edges of the image, which do not exist in the Ilastik-segmented image (see below), and assigned to different brain areas.
They appear aligned to the edges but, after zooming in, I noticed that they have slightly different distances to the edge.

![segmentation](https://user-images.githubusercontent.com/86107186/126360309-390bc4b6-5fb0-454b-966f-f22a4ee12b2d.png)

**Comment by sharoncy** [comment]
I don't have enough information here to be able to investigate. @Wissewald Would you be able to send an example atlas map, segmentation, XML/JSON and Nut file and point out the objects that do not exist in the segmentation? You can contact me directly at s.c.yates@medisin.uio.no. Thanks!
(Sharon Yates)
