### ISSUE TITLE
Bug in Nutil v0.6.6

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#228]
Nutil v0.6.6 is not working as it should. I tried to run an analysis with AMBA v3 (2015) and got the error message below. Nutil stopped working all together shortly after. I ran the same analysis with Nutil v0.6.0 (identical NUT file, identical images) and that analysis ran as it should. We have seen something similar for WHSv3, Nutil v0.6.6 didn't run, whilst Nutil v0.6.0 did. We shouldn't release this version officially until we have resolved this issue. 

![bilde](https://user-images.githubusercontent.com/30626642/133424498-38fc8cea-c35f-4418-b9e1-ada15f2335fc.png)

Another thing with v0.6.6: this extra row gets added to the GUI every time Nutil runs. 

![bilde](https://user-images.githubusercontent.com/30626642/133425221-8b5d4cb4-3caf-4274-a29b-f340816db720.png)

**Comment by leuat** [comment]
Could you send me this data set (with the file that is not working)? Probably qt6 stuff, we'll see...

**Comment by sharoncy** [comment]
Sure. I'll prep some files and forward to you.

**Comment by leuat** [comment]
Bug fixed, increased the internal Qt6.0 image size limit
