### ISSUE TITLE
custom mask color in the nut file

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/nutil#235]
Hi,
Even when the feature custom mask is not selected, the custom_mask_color = 255,255,255,255 is displayed in the nut file.
Does it mean that this mask color is selected by default or should this line not be present in the nut file when custom mask=no is chosen?

**Comment by sharoncy** [comment]
Sounds good. I already have FAQ for the ilastik part of the readthedoc. We could follow a similar structure for the other software: https://nutil.readthedocs.io/en/latest/Ilastik.html#faq-and-troubleshooting
