### ISSUE TITLE
Expand info about the NUT file to the ReadtheDocs

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#237]

**Comment by sharoncy** [comment]
Some info added here: https://nutil.readthedocs.io/en/latest/QuantifierOutput.html#nut-file
This can be expanded if necessary.

**Comment by Majpuc** [comment]
I guess the information about the NUT file is now in place. Can we close this issue ? @sharoncy

**Comment by sharoncy** [comment]
Close 31.05.22
