### ISSUE TITLE
Object report sorted by custom regions

### ISSUE THREAD

**Issue by ingvildeb** [Neural-Systems-at-UIO/nutil#239]
Hi,

It would be great to add an object report sorted by custom regions. I think most if not all users who use custom regions for their quantifier reports will have high interest in a corresponding object report. I think it can contain basically the same columns as the "All" file (except of course the region ID). Here is an image of the current _All report: 

![image](https://user-images.githubusercontent.com/28010291/141435544-d75dfac9-355d-4c36-baf2-4df468b9ae94.png)

A custom report could instead of region name give the custom region. 

Alternatively, if this is simpler, adding a column to the current _All report giving the custom region to which the region ID of the object is sorted would also solve this.

Best, Ingvild

**Comment by sharoncy** [comment]
Thanks for the suggestion, it's great to hear you use this report! The object report hasn't received as much attention as the others so agree it could do with some updating. Is this something you need soon, or just an idea for the future? If it's something you need for data you are currently working on we'll give it a higher priority.

**Comment by ingvildeb** [comment]
I will use it for my data now (soon), so would be great if you could prioritize it. 

As a note, I'm using these reports to create summary statistics on the object pixels, to use for calculations of cell densities, but the excel files are really heavy since all objects across the brain are listed (when running quantifier on segmented cells across ~half a mouse brain, I get > 700 000 rows). It is of course relatively easy to write a code to draw such statistics, but might be something that could be interesting to add a report on in the future.

In the short run, sorting the current report based on custom regions (as described in the entry above) would be immensely helpful for my use case.

**Comment by leuat** [comment]
<img width="1113" alt="Screenshot 2021-11-19 at 10 25 21" src="https://user-images.githubusercontent.com/5620670/142598805-80cb0743-8ff9-40e9-9c4c-e41461b739e2.png">

@ingvildeb was this what you had in mind? If the current ID is contained in one of the reports, the report name will be written in the 8th column. Please let me know whether this is what you asked for =)

**Comment by ingvildeb** [comment]
Yes. I assume though that the custom region name (in the 8th column) would be from the custom region file (and not the default custom regions as shown here), given that such a file is specified?

**Comment by leuat** [comment]
<img width="1095" alt="Screenshot 2021-11-19 at 14 25 51" src="https://user-images.githubusercontent.com/5620670/142630178-d3a22746-bf7e-4f21-bc94-3453cd5e9f2e.png">

Jupp! Here I switched from default to a custom region file, with my own highly useful naming convention

**Comment by ingvildeb** [comment]
Wonderful, this is exactly what I had in mind 😄

**Comment by leuat** [comment]
@ingvildeb because this added column will break the automatic validator, Sharon will have to updated the ground truth files before a new release can be successfully (and automatically) built. For now, here's a special version for you: https://www.irio.co.uk/L/nutil.rar. Let me know if it works, I just compiled it up on a brand new windows install, so I have no idea if it works or not. 

@sharoncy just pull from github and build in qt as usual. Let me know when the ground truth data is updated, we can then trigger a new release. are some other minor changes as well.

**Comment by ingvildeb** [comment]
Thanks, I've tried it out now. Seems to work perfectly!


By the way, I ran into trouble because I moved my custom regions file after creating the nut file so the directory was wrong. In this case, nutil ran through everything but the custom regions reports were just empty. Maybe a bit strange behavior, I would have expected an error message given that it did not find my custom regions file?

**Comment by sharoncy** [comment]
The main issue is closed here. Ingvild suggested an error message improvement: not a priority now, but will look into this at a later date.

**Comment by ingvildeb** [comment]
Done!

**Comment by Majpuc** [comment]
Thanks!!
