### ISSUE TITLE
Improve Read the Doc - Nutil coordinates do not take into account nonlinear transformation

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#242]

**Comment by Majpuc** [comment]
Hi @sharoncy Would it be possible to add this important information to the ReadtheDocs before the review?

**Comment by sharoncy** [comment]
I've added the info to the coordinate section (it may take some time to update) https://nutil.readthedocs.io/en/latest/QuantifierOutput.html . Let me know if you'd like the info anywhere else.

**Comment by sharoncy** [comment]
This is done. close 19.01.22
