### ISSUE TITLE
Implement support in NutilWeb for WebAlign .json file structure. 

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#244]
To enable NutilWeb integration with WebAlign: implement support in Nutil for the .json file structure supported by WebAlign. This file structure is not yet finalised, so we should keep in touch about this @leuat @Tevemadar .

**Comment by Tevemadar** [comment]
A thing to point out: this is very much an emergency format and is considered temporary. It was created only to be able to simulate the "feel" how a user would start working on their own data. Which is not their own at the moment, but a pick from the ~200 ingested series which we know about being available in the image service, and the format is tailored to this single, fabricated purpose. Of course it somewhat resembles the descriptors we have in use, but it will get changes for sure.  
Example of 2 sections, one without, and one with anchoring:
```
{
   "name":"Coronal distribution of myelin in Mouse (case 2565)",
   "container":"https://object.cscs.ch/v1/AUTH_08c08f9f119744cbbf77e216988da3eb/imgsvc-eb005677-6cef-4b33-b184-6abdfb590c41",
   "kg":"https://search.kg.ebrains.eu/instances/Dataset/63bbb845ac6d2f1839f919c2ef0455bc",
   "atlas":"WHS_SD_Rat_v3_39um",
   "sections":[
      {
         "name":"hbp-00167-641_2002_2565_s001.tif",
         "width":14500,
         "height":9500,
         "tilesize":254,
         "overlap":1,
         "format":"png"
      },
      {
         "name":"hbp-00167-641_2002_2565_s025.tif",
         "width":14500,
         "height":9500,
         "tilesize":254,
         "overlap":1,
         "format":"png",
         "ouv":[
            -2.502687899090688,
            530.8287357577043,
            457.0371474341125,
            480.5526876772498,
            0.2857198444359374,
            11.414723660201405,
            15.350029366555203,
            -8.944832344462897,
            -357.3528104092402
         ]
      }
   ]
}
```

**Comment by Tevemadar** [comment]
Ah, mouse sections registered to rat atlas, no wonder they look a bit off.

**Comment by Majpuc** [comment]
No longer needed.
