### ISSUE TITLE
Issue with Tiff creator from untiled Tiff to tiled Tiff

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/nutil#246]
Hi,
It seems that tiff creator is not working properly in v0.70. I first had problems with my images and then repeated the error with the test dataset "Example2" located  at Z:\HBP_Analytics\Nutil\Nutil_testing\TiffCreator_testdataset\Example2_Tiff_to_tiled TIFF and get a 1kB file. Did I miss something? I haven't used it for a long time. Could you have a look at this?
Thanks!

**Comment by sharoncy** [comment]
We'll investigate and get back to you.

**Comment by Majpuc** [comment]
Hi, Thanks Sharon for testing!
I managed today to obtain the tilled Tiffs. I cannot see the explanation for this previous error. You may close this issue.

**Comment by sharoncy** [comment]
Great, thanks. Issue closed. 11.03.22.
