### ISSUE TITLE
Crashing when trying to process multiple sections (possibly due to RAM?)

### ISSUE THREAD

**Issue by jaimemcc** [Neural-Systems-at-UIO/nutil#249]
Hi,

I am trying to use the Quantifier function of Nutil on a Windows PC with 32GB RAM. It works pretty well for single sections from my project but when I try with whole brains it crashes without any error message. When using the GUI all processes just terminate without adding any comment to the log and when in CLI I get the message that "All .nut files processed. Have a nice day :)".

I have a suspicion that it could be due to RAM because with a single section it requires approx 3-4GB and I am trying to run it on a series of 40 sections. As a workaround I have considered writing a script to generate .nut files and folders for each section at a time but would like to avoid this if at all possible. My segmentation files are 8-bit binary PNGs that are 40-150kb and max size 7000 (w) x 5000 (h).

I can provide more information about the project if useful.

**Comment by leuat** [comment]
Sounds like a RAM problem yes! You should view your memory usage in task manager - remember that Nutil will automatically try to run the batch on the number of threads in your CPU - if each thread suddenly uses 4-8gb, you might get into trouble.

You can lower the number of threads used in a nutil batch either via the command line - or simply setting your preferred number of threads in the main window (right next to the "user documentation" button)

**Comment by leuat** [comment]
try lowering to 1 or 2 or 4

**Comment by jaimemcc** [comment]
Thanks for your reply! In the end, it seems that it wasn't actually a RAM problem but something completely unrelated about the JSON anchoring file. When I switched to the XML file it works great even with all 6 cores. I'm not sure what the problem with the JSON file was - I have inspected it and it appears to contain the same info as the XML file.

**Comment by Majpuc** [comment]
Dear jaimemcc,

Sorry for the late reply but we hope your issue was resolved. Do not hesitate to contact us again if you encounter issues by opening a new ticket. Best regards, Maja
