### ISSUE TITLE
Per object point cloud

### ISSUE THREAD

**Issue by PolarBean** [Neural-Systems-at-UIO/nutil#274]
Give nutil the ability to output one point per object as well as one point per pixel. Both are very useful metrics, it would be nice if nutil could automatically output one point per object when object counts are selected. This would make compatibility with https://github.com/brainglobe/brainrender easier as well as enable some quantitative workflows which require object position.

**Comment by leuat** [comment]
Implemented. Average center point used

**Comment by PolarBean** [comment]
Thats great!! so it gives an option? As one point per object and one point per pixel are both needed
