### ISSUE TITLE
Issue with Nutil Customized Reports - Localizing One Object to Multiple Atlas Regions

### ISSUE THREAD

**Issue by RanaAbdelhalim** [Neural-Systems-at-UIO/nutil#275]
Hello,
My work is in stroke, and I am trying to localize a lesion (a single object/shape/blob) to multiple atlas reference regions. This is to find out what percentage of each of these regions ( for ex: secondary motor area, primary motor area, somatosensory area, etc) is impacted by the lesion.
**My issue arises with the Custom Regions Reports obtained from the Nutil Quantifier Tool:** 
The following zip folder contains my Nutil input files (Segmentation folder, Brain atlas map folder, JSON anchoring file, and the Custom regions file) and output files:  [Unsuccessful Nutil Results.zip](https://github.com/Neural-Systems-at-UIO/nutil/files/10367278/Unsuccessful.Nutil.Results.zip)

- Since I am interested in specific regions of interests, I used the QCAlign tool and the provided template on the [Nutil documentation website](https://nutil.readthedocs.io/en/latest/QuantifierReports.html) to create my own list of custom regions (called: "QCAlign_Custom_regions.xlsx").

- Once the operation has successfully completed running and I obtain my results, I notice that there is an error in the Custom Regions files and the Coordinates JSON file.

- **Issue with Custom Regions Reports:** It appears that the program is only recognizing the object in the secondary motor area which has an object count of 1. Resulting in all of the object (lesion) pixels being assigned to the secondary motor area.
- This is an issue because this lesion also extends to the primary motor area, but the object pixels that should be assigned to the primary motor area are instead being assigned to the secondary motor area.
- I think this is happening because I am try to localize 1 large object (the lesion) to multiple regions.

- **Issue with Coordinates JSON file:** Similar to the issue with the reports, the coordinates of the object (the lesion) are all being assigned to a single index, secondary motor area, even though some of these coordinates should actually be assigned to the index of the primary motor area.

**My question is:** 
Is there any way around this, so **is there any way for me to localize a single object to multiple atlas regions?**
If not, is there a way perhaps in the script to either exclude, avoid, or adjust the object count so that either:

**1. We don't use the object count at all when assigning the object to the index of an atlas region? And just allow the object pixels to be distributed among multiple reference atlas regions.**

Or
**2. We allow a single object to be assigned to multiple regions at once?** _I assume in the current script this currently prohibited so that objects aren't counted twice for instance. But in our case, it would be preferable to override that._

Thank you so much in advance for you help! And apologies for the long message!

**Comment by sharoncy** [comment]
Hi. Great to hear that you are using the QUINT workflow and the new QCAlign tool. How did you hear about the tools?  The feature you request is already supported in Nutil. To assign each object pixel to the correct atlas region, select "Yes" for "Object Splitting" in Nutil Quantifier. This ensures correct calculation of the regional coverage. See more information here: https://nutil.readthedocs.io/en/latest/QuantifierOS.html. 

Let me know if you have any more questions. 
Best wishes,
Sharon Yates

**Comment by RanaAbdelhalim** [comment]
Hi Sharon, thank you so much for your reply, I think it works well now!
I heard about the tools through your publications and also attended the "Neuroscience data integration through use of digital brain atlases" IMB9345 that was held by your research group.

Thanks again,
Rana Abdelhalim

**Comment by Majpuc** [comment]
Dear RanaAbdelhalim,

Thank you for using our tools. Do hesitate to create a new ticket if you have more questions.
Best, Maja
