### ISSUE TITLE
Error: Report must have unique names for : _s

### ISSUE THREAD

**Issue by taminastelzer** [Neural-Systems-at-UIO/nutil#277]
Hi,

thanks for this amazing tool. I really would like to use it for my analysis. However, I encountered some issues. I followed the QUINT workflow: Atlas Registration with DeepSlice, QuickNII -> object segmentation with Ilastik -> Now I want to do the quantificaiton with Nutil using the generated data.

I labeled all the files in the mentioned way (_sXXX). Nevertheless, I receive following error message in Nutil:
**Error: Report must have unique names for : _s**

**Labeled Files Input for Nutil**

![Labeling Segmentation](https://user-images.githubusercontent.com/95414450/214553089-0097a604-6b9c-4c90-8b0a-8f26dddc36db.png)
![labeling atlas-brain](https://user-images.githubusercontent.com/95414450/214553093-1c64c42b-0ff2-43c8-9b26-ffc39fa996d8.png)

Thanks a lot!

**Comment by sharoncy** [comment]
Hi. Glad to hear you're using the tools. If you send me a segmentation, corresponding atlas map, the .xml or .json file from QuickNII and your .nut file from Nutil I'll investigate further. Email s.c.yates@medisin.uio.no
Sharon.

**Comment by WelcomeKon** [comment]
Hi, i have a similar issue. It specifically notes:
_Error: Report must have unique names for : _s019_
![image](https://user-images.githubusercontent.com/65562624/232291575-6db2504e-7649-4a5c-ae9f-dd3f24c4db9c.png)

But this is already the unique ID I created.

![image](https://user-images.githubusercontent.com/65562624/232291547-d5338502-886e-4389-bdf1-b57566ac969d.png)

As a result I dont get any reports just these few images:
![image](https://user-images.githubusercontent.com/65562624/232291620-218f34e0-6a94-42de-9e85-120e5249b3e4.png)

Is there something, that I am missing?

Thanks in advance for any help.
Konstantin.

**Comment by Majpuc** [comment]
Could you have a look at this @sharoncy ?

**Comment by sharoncy** [comment]
Hi Konstantin, I agree that the segmentation looks like it's been named correctly. The unique ID must also be present in the xml/json file from QuickNII or VisuAlign and in the corresponding atlas map. If you send me an example dataset (the xml or json from QuickNII/VisuAlign, the segmentation with ID: _s019, atlasmap with ID_ _s019 and a copy of the .nut file from Nutil), I'd be happy to investigate for you. Email s.c.yates@medisin.uio.no

Another point. Since you are working with hemibrain sections, it's also good idea to run your analysis with masks to exclude the missing tissue. These can be automatically generated with the QuickMask application (available on nitrc with the QuickNII or VisuAlign software) (https://nutil.readthedocs.io/en/latest/QuantifierMasks.html). If you send me the files above, I can also give you a demo of this,

Best wishes
Sharon

**Comment by WelcomeKon** [comment]
Thank you very much for the quick answer! I have sent the files as requested and I will take a look at the Quick Mask application!

**Comment by inininNotFound** [comment]
Hello, I am having a similar issue too, can you help me take a look pls? Thank you!
![Capture2](https://github.com/Neural-Systems-at-UIO/nutil/assets/106695763/c45e6742-da64-4005-9763-77d58fea433e)
![Capture3](https://github.com/Neural-Systems-at-UIO/nutil/assets/106695763/d91cf338-c87e-47fa-a664-958af43393b5)
![Capture](https://github.com/Neural-Systems-at-UIO/nutil/assets/106695763/72bad842-cce2-4ed9-9770-dcf8c2a7fd44)

**Comment by inininNotFound** [comment]
> Hi @inininNotFound. In order to work, Nutil requires atlas maps in .flat format, segmentation files in .png format and the .json file from VisuAlign containing the registration information. It looks like you have followed the naming convention correctly (_s11), but I don't see the atlas map or segmentation file for this section in the screenshot (these should be named: "_s11_nl.flat" and "_s11_simple_segmentation.png". First, could you check that you have these files in place and in not, do a re-run? If this doesn't fix the problem, feel free to send me the files for one section (atlas map, png and json) and I'll test it out for you. Best regards, Sharon Yates, [s.c.yates@medisin.uio.no](mailto:s.c.yates@medisin.uio.no)

Hello, I added the missing file and it still didn't work. I sent you my files. Can you help me take a look? thank you!
