### ISSUE TITLE
There are no object counts in the reports (N/A)

### ISSUE THREAD

**Issue by nleonreyes** [Neural-Systems-at-UIO/nutil#279]
Hello, after running Nutil I get the following message: 
Mon Feb 13 13:00:10 2023 : Required memory: 1.60217 GB. Free memory : 32605 GB from a total of 32605 GB installed (0 %) usage
Mon Feb 13 13:00:12 2023 : ****** Count of pixels 0
Mon Feb 13 13:00:12 2023 : ****** Count of pixels 0

I already check and set the option "Object Splitting" = NO 
But still having no object counts. Does anyone face the same problem before? Maybe something is wrong related to the segmentation process. Thanks in advance, any help is welcome ;)

**Comment by nleonreyes** [comment]
And this is the Nutil_program output I get: 

****** Count of pixels 0"
QIODevice::read (QFile, "\\..\\plot\plot_reference_atlas_regions.py"): device not open
QIODevice::read (QFile, "\\..\\plot\plot_custom_regions.py"): device not open
QIODevice::read (QFile, "\\..\\plot\plot_lib.py"): device not open

**Comment by sharoncy** [comment]
Hi. Thank you for your interest in Nutil. To investigate further I'll need some example files, please send at least one segmentation, a corresponding atlas map, the xml/JSON file from QuickNII or VisuAlign containing the registration info, and a copy of your .nut file to support@ebrains.eu  (include a reference to Brain atlas services and Sharon Yates in the email). I'll get back to you as soon as I can.

**Comment by nleonreyes** [comment]
Hi, thank you so much for the quick reply, finally, I found the error, it was something very simple, I was introducing a wrong color code for the detection with Nutil, and once I replace the proper color code everything worked perfectly. Sorry for the spam, And thanks again for such a great tool
