### ISSUE TITLE
count of pixels 0

### ISSUE THREAD

**Issue by AthiemoneZero** [Neural-Systems-at-UIO/nutil#285]
Hello. I encountered such a problem when I use the nutil quantification tool in the QUINT workflow. 

"LOG: Generating summary report"

"LOG: Creating summary "
"LOG: Generating sheets "
"LOG: Saving report to I:/CXC/QUINKworkflow/projects/20054/quan/\\Reports\\nutilQ_CustomRegions.xlsx"
"LOG: Releasing I:/CXC/QUINKworkflow/projects/20054/quan/\\Reports\\nutilQ_CustomRegions.xlsx"

"MESSAGE: ****** Count of pixels 0"

"MESSAGE: ****** Count of pixels 0"
QIODevice::read (QFile, "\\..\\plot\plot_reference_atlas_regions.py"): device not open
QIODevice::read (QFile, "\\..\\plot\plot_custom_regions.py"): device not open
QIODevice::read (QFile, "\\..\\plot\plot_lib.py"): device not open

The output seems not to generate any useful Images in PNG format accounting for the signals as well as the Coordinates in JSON format (which are 1kb appeared in the Coordinates subfolder but I cannot find any signals in them when I open on meshview web). But I can find out the  Reports in CSV format.

Any suggestion would be greatly appreciated!

**Comment by AthiemoneZero** [comment]
BTW. I've check the issue#279 which seems similar to my problem. But This just solved the problem of counting (generate useful Images in PNG format accounting for the signals ) and  it report the same problem of QIODevice like here:

"LOG: Type of operation: Quantifier"
"MESSAGE: Required memory: 2.29986 GB. Free memory : 98004 GB from a total of 98004 GB installed (0 %) usage"
"LOG: Executing..."
QFile::copy: Empty or null file name
"LOG: Generating summary report"

"LOG: Creating summary "
"LOG: Generating sheets "
"LOG: Saving report to I:/CXC/QUINKworkflow/projects/20054/quan/\\Reports\\nutilQ_CustomRegions.xlsx"
"LOG: Releasing I:/CXC/QUINKworkflow/projects/20054/quan/\\Reports\\nutilQ_CustomRegions.xlsx"


"MESSAGE: ****** Count of pixels 329464"

"MESSAGE: ****** Count of pixels 329464"
QIODevice::read (QFile, "\\..\\plot\plot_reference_atlas_regions.py"): device not open
QIODevice::read (QFile, "\\..\\plot\plot_custom_regions.py"): device not open
QIODevice::read (QFile, "\\..\\plot\plot_lib.py"): device not open

**Comment by leuat** [comment]
Hi there! This message means that the Nutil python plot files is not found internally.. in order to get python plots generated automatically, please make sure that: 
- you are running "Nutil.cmd" from the "nutil" directory - *not* the .exe file in the program folder
- the .py plot files exist in the /plot directory
- that you are not running from some external file system that have trouble reading files over the network...

regards

Nicolaas

**Comment by AthiemoneZero** [comment]
> 

Very thankful for your timing reply! 

I go back and make sure I did run "Nutil.cmd" from the "nutil" directory  (I even did not notice the .exe file in the program folder : ). And py plot files they are there so far. As for external file system, I am a little confused here as I am not sure if I ve used it. 

Although the bug is reported anyway, I am surprised to find out it somehow can plot the py plot. Strange again but I have no idea how it can work.

Best and yours

**Comment by sharoncy** [comment]
To get the python plotting feature to work, you also have to install Python on your computer as well as the following Python packages: numpy, pandas and matplotlib. (see: https://nutil.readthedocs.io/en/latest/Technical.html). This is a new feature in Nutil, which is useful for getting an overview of your data, but is by no means a necessary part of the QUINT workflow.  If you have problems with it, you can just ignore this part and generate your own plots based on the reports.

**Comment by AthiemoneZero** [comment]
> To get the python plotting feature to work, you also have to install Python on your computer, as well as install the following Python packages: numpy, pandas and matplotlib, and adjust some settings in Nutil (see: https://nutil.readthedocs.io/en/latest/Technical.html). This is a new feature in Nutil, which is useful for getting an overview of your data, but is by no means a necessary part of the QUINT workflow. If you have problems with it, you can just ignore this part and generate your own plots based on the reports.

yeah. I make sure I set the path of python executor to a python.exe which can work independently with these three packages. I finally set the path to my anaconda python.exe and it looks like that can help plot the figures out.

Of course this plotting function is very great and useful and I find it can make something direct to brain signal mappping. I really like this function and it eventually can work although with some warnings in the terminals.

I think this issue somehow won't be a issue any more. Thanks all of you and really grateful for your help!
