### ISSUE TITLE
Add metadata to coordinate file from Nutil

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#289]
Request to add metadata fields to the coordinate files from Nutil:
- name of atlas
- whether one point per object or one point per pixel
- Nutil version

**Comment by leuat** [comment]
Have added it to the code, but commented out because metadata in the .json files seems to break meshview. G will probably have to have a look at this, to allow meshview addition unrelated json entries

**Comment by leuat** [comment]
Implemented
