### ISSUE TITLE
Nonlinear coordinates - fix error to speed up extraction

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#292]
Gergely pointed out that coordinate extraction is not set up optimally in Nutil,  it recalculates the deformation field for each pixel (only needs to be done once). I don't understand the details here, great if @leuat and @Tevemadar could discuss and get this fixed.

**Comment by Tevemadar** [comment]
A possible modification is that I move the triangulation so it happens immediately when the descriptor file is loaded.

**Comment by leuat** [comment]
This has been implemented. The CoordinateTransform object is now shared in a map, and will only be initialised on creation.
