### ISSUE TITLE
Fix up error message 

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#294]
I got this error message for Example1_CCFv3_2015_CrossSeeds_long, AMBA 2015. Not sure what it means. 

![Unrecognised atlasmap](https://user-images.githubusercontent.com/30626642/233948091-bd50ee28-70c7-4587-9294-ce31efd47d07.PNG)

**Comment by Majpuc** [comment]
Not possible to fix now
