### ISSUE TITLE
Transform and TiffCreator jpeg compression issue

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/nutil#296]
Hi,
Tiff Creator fails to work for jpeg compression. Maybe it requires a new jpeg compression library?
Test dataset in Nesys drive, Nutil test datasets, Tiff creator, example 2.
![image](https://github.com/Neural-Systems-at-UIO/nutil/assets/46992863/8586a901-f62f-4b52-8428-09ea5e9c1bd5)

**Comment by Majpuc** [comment]
If I choose jpeg compression in transform, the sw just crashes.

**Comment by sharoncy** [comment]
@leuat I did a test with Nutil v088 and tiffcreator doesn't work for either jpg to tiled tif (with jpg compression), or tif to tiled tif (jpg compression). In my case it didn't crash but created corrupt images (they wouldn't open, and the image size was much smaller than expected). I used the standard images that we have used in the past for testing. Let me know if you'd like me to sent them to you.

**Comment by sharoncy** [comment]
This issue has been fixed in Nutil v0.8.9. Issue closed 15.08.23.
