### ISSUE TITLE
Add metadata field to Meshview file with centroid or all pixels

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#300]
There is a request for a metadata field in the coordinate output json from Nutil stating whether it corresponds to all pixels or centroid of objects. They have to remain compatible with Meshview. Harry and I tested adding {"type": "per_object"} to the coordinate file and it opened fine in Meshview. We can check with Gergely on Friday on the best way to do this, would be good to have this in the next Nutil version.

**Comment by leuat** [comment]
implemented. json files now have this additional extra output:

{
"metadata" : {
	"atlas:" : "WHS Atlas Rat v3",
	"area_type:" : "area", 
	"nutil_version:" : "m1 ARM experimental version 0.801"
}
