### ISSUE TITLE
Nutil keeps crashing for some reason 

### ISSUE THREAD

**Issue by nikesilvermoon** [Neural-Systems-at-UIO/nutil#302]
I really have no idea why. I was trying to quantify Abeta stains and realized that I had to redo the JSON file. And then I regenerated the appropriate segmentation and brain atlas files. I also double checked the file names to make sure that they all end with s0001. So everything is cool up until I press "start". Then nutil just crashes. The report folders were generated in my output folder (Coordinates, Image, etc), but none of the actual outputs. I'm using a Windows 11 laptop. Any insights? Thank you!

**Comment by Majpuc** [comment]
Hello,
Let's try to figure this out. Did you successfully obtain quantifier results with your previous registration and segmentation files?
Which Nutil version are you using? Do you use masks? Could you provide a few atlas maps, registration JSON and segmentation files as well as your .nut file for us to troubleshoot?

**Comment by sharoncy** [comment]
Hi @nikesilvermoon. The most common cause of Nutil crashes is that Nutil loses the connection with the images during the processing time. This can happen if Nutil is saved in a different location to the images (for example, Nutil on the local C: drive and the images on a separate University server). Try saving both Nutil and the images to be processed on the C: drive and try again. If the problem repeats, I will be happy to investigate for you but I will need an example dataset so I can test. This should include your json file from QuickNII or VisuAlign, an atlasmap and segmentation corresponding to a section and the NUT file from Nutil containing your Nutil settings. You can email me at s.c.yates@medisin.uio.no
