### ISSUE TITLE
Nutil not opening/Crashing

### ISSUE THREAD

**Issue by humashaheen** [Neural-Systems-at-UIO/nutil#303]
Hi,
I have downloaded Nutil 0.8.7 and it is crashing immediately before I can open it. What could be the issue?

**Comment by sharoncy** [comment]
Hi @humashaheen, sorry to hear you're having problems with Nutil. I am not sure why this is happening in your case. Some things you can check. The Nutil download is a zipped archive file so save it locally (on the C: drive) and extract the files by right clicking on the zipped folder and selecting "extract all". Once it is extracted, click the Nutil.cmd file to open. Sometimes computer have security settings that stop it opening. In this case, right click on the nutil.cmd file, select "properties", check  “unblock” under "Security". If that doesn't solve it, try installing Nutil on a computer for which you have admin rights. Does this problem also occur with Nutil v0.8.0? This is our latest stable version.

**Comment by humashaheen** [comment]
hi
Thank you for replying. Unblocking the security did not solve the problem and I am having this issue with v0.8.0 too.

**Comment by humashaheen** [comment]
hey Sharon,

Nutil is working now. 

Thank you

**Comment by humashaheen** [comment]
Hi 
It started working when I opened it from the unzipped folder of nutil, program and then nutil_program.exe. 
It was crashing when I tried to open it from nutil.cmd ( previously worked though). 

Thanks.

**Comment by sharoncy** [comment]
Issue closed 10.08.23
