### ISSUE TITLE
Metadata field in coordinate.json - bug or not supported?

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#307]
A new "metadata" field has been implemented in the coordinate.json output from Nutil (Nutil v0810). The files no longer open in Meshview.  Is there a bug in the way it was implemented, or is it not supported to have extra parameters in Meshview?

![image](https://github.com/Neural-Systems-at-UIO/MeshView-for-Brain-Atlases/assets/30626642/e347e952-6f87-40d1-af73-c1829357bbbb)

**Comment by leuat** [comment]
Added a trim when loading the string. hopefully this will have fixed the issue, please reopen if not
