### ISSUE TITLE
Containerized version?

### ISSUE THREAD

**Issue by zackramjan** [Neural-Systems-at-UIO/nutil#310]
Any chance this could be distributed as a docker/singularity/apptainer container, or perhaps create a working Dockerfile?

We would like to run this in an Rhel-dervied HPC environment, but there are many deps to nutil that could probably be handled fairly nicely by wrapping it in a container.

**Comment by sharoncy** [comment]
Hi, sorry the for late reply. I agree that it would be useful to distribute Nutil as a docker container. But unfortunately, we don't have capacity to implement this now.
