### ISSUE TITLE
Nutil keeps crash while quantifying

### ISSUE THREAD

**Issue by YANGBYUNGJUN201** [Neural-Systems-at-UIO/nutil#314]
Sorry for keep bothering... I hope this would be my last question.

I am now processing 111 images with nutil quantifier. It works well at first, but it crashes when process reaches about 50%. I dont know why because no error message shows up. It just crashes without any notice. 

I tried to lower the number of threads to 2 or 4, and it crashed again. I changed my computer which has 32GB RAM, to computer with 64GB RAM, and it did not work. 

Is there any way to figure out this problem? I am submitting with segmentation file, flat file, and anchoring file. (dividing segmentation files in 3 zip files because of 25MB limit)

[brainatlas.zip](https://github.com/Neural-Systems-at-UIO/nutil/files/13556942/brainatlas.zip)
[segmentation1.zip](https://github.com/Neural-Systems-at-UIO/nutil/files/13557001/segmentation1.zip)
[segmentation2.zip](https://github.com/Neural-Systems-at-UIO/nutil/files/13557003/segmentation2.zip)
[segmentation3.zip](https://github.com/Neural-Systems-at-UIO/nutil/files/13557004/segmentation3.zip)
[76-2ROI(greenonly)1204MyResults.json](https://github.com/Neural-Systems-at-UIO/nutil/files/13557014/76-2ROI.greenonly.1204MyResults.json)

**Comment by sharoncy** [comment]
Sorry to hear you're having problems. I tested with the files you sent and got it to work successfully with Nutil parameters that I selected myself. If you send me a copy of your .NUT file (from Nutil), I can do a test run with the parameters that you selected. Which version of Nutil did you use?

I have attached some of the results from my analysis, but wasn't able to attach everything as the results were too large. If you send me your email address I'll forward everything (you can contact me at s.c.yates@medisin.uio.no).

[Reports.zip](https://github.com/Neural-Systems-at-UIO/nutil/files/13612806/Reports.zip)
[Plots.zip](https://github.com/Neural-Systems-at-UIO/nutil/files/13612807/Plots.zip)

Some tips:
- If Nutil loses connection with the files while running it will crash, so make sure the Nutil software and files are stored locally and in the same place (C: drive is good).  
- Try switching off the coordinate extraction in Nutil, this is the most time consuming step and may have contributed to the crash.
- I also had problems with Nutil crashing for your dataset, but it crashed after the analysis had completed (not at 50%), which means that all the results compiled correctly and were available in the output folder. I have reported the crashing problem to our developer, I'm not sure why this is happening. 
- I briefly looked at your results and think it should be possible to improve the feature extraction using the pixel classification followed by object classification in ilastik (to remove non-specific labelling - if required), and to improve the atlas-registration using VisuAlign. Although of course up it's up to you how much time you want to spend on these steps. 

Good luck with your analysis
