### ISSUE TITLE
Measure total fluorescence

### ISSUE THREAD

**Issue by Noy987** [Neural-Systems-at-UIO/nutil#316]
Is it possible to measure intensity of total fluorescence and in scans of mice brain slices within the program?
If so, is it possible to measure multiple colors and their intensity in the same scan?

Any guidance and tips would be greatly appreciated. Thank you very much!

**Comment by Majpuc** [comment]
Dear Noy,

Our software don't provide a mean of measuring fluorescence intensity in your brain sections, only to quantify labeling.
As I answered to a similar question here https://forum.image.sc/t/signal-thresholding-on-whole-brain-slices/87123/22
One should be cautious when using fluorescence signal to quantify protein density as the signal is not completely linear.
It is possible when microscopic settings are considered before taking the images.

I hope this helps!

Best, Maja

**Comment by Noy987** [comment]
Okay, I will look at the link, thank you very much!
