### ISSUE TITLE
Problem about "count of pixels 0" from process output

### ISSUE THREAD

**Issue by soomin2189** [Neural-Systems-at-UIO/nutil#318]
Hi, I am currently using QUINT workflow for quantifying stained cells from a mouse brain.
I've been trying to run Nutil with my data, however, I kept getting a message that 'Count of pixels: 0'.
I'm not sure why this error happens even though I turned off the object splitting and set the python path correctly.
Another weird thing is that the software did run but did not count the cells.

![001](https://github.com/user-attachments/assets/b59b1236-6b11-4828-a210-fb11ad76cb7b)
![002](https://github.com/user-attachments/assets/a757f883-4077-4c45-b1d3-a50fe7fb8dea)

These are the screenshots from my Nutil software. 
Thank you!

**Comment by sharoncy** [comment]
Hi @soomin2189. It looks like Nutil has run as it should, but has failed to detect any objects. In the Nutil software, the objects-of-interest are specified using an RBG colour-code, so the fact it isn't finding any suggests the colour specified in Nutil (the RGB colour code) isn't found in your segmentations. A common pitfall here is that the segmentations have been generated with the ilastik software, but they haven't been colourised using the Glasbey LUT (https://quint-workflow.readthedocs.io/en/latest/Ilastik.html#applying-the-glasbey-lookup-table). If this is the case here, apply the Glasbey LUT using Fiji and then try again. If you've already done this step, please check that the RGB code specified in Nutil and in your segmentations match exactly. If you still have problems, I'd be happy to troubleshoot for you (send me an example dataset with all the required input files to s.c.yates@medisin.uio.no). Best regards, Sharon

**Comment by soomin2189** [comment]
Hi Sharon,

Thank you for the advice! I solved the issue and I think the issue happened
because I didn't choose the right RGB colour code when I tried to run
Nutil. After converting my images using Glasbey LUT and assigning the exact
object colour, it worked!

Thank you for helping me again!


Best,
Soomin

2024년 7월 29일 (월) 오후 8:41, Sharon Yates ***@***.***>님이 작성:

**Comment by sharoncy** [comment]
Issue solved, closed 06.08.24
