### ISSUE TITLE
Request for Feature to extract custom coordinate json

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#33]
Martin would like to extract coordinate files that include coordinates for the custom regions only (it is time consuming to extract all coordinates and then switch off regions in Meshview).

**Comment by Majpuc** [comment]
We don't have capacity to implement this. This can be achieved by post-processing of the actual coordinate files. We close this issue now, please send a new issue if this is still required. 25.08.2021
