### ISSUE TITLE
Request for postprocessing analysis for comparing coordinates from many dataset

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/nutil#37]
Trygve/Martin hves made a request for an analysis pipeline for comparing coordinate outputs. This needs some discussion.

**Comment by leuat** [comment]
Soooo... what is this all about? Need some more info!

**Comment by sharoncy** [comment]
No need to look at the low priority issues now - the priority and in process issues are the ones that need doing prior to the next release.

**Comment by Majpuc** [comment]
This is about a new tool for Martin to compare point cloud outputs

**Comment by sharoncy** [comment]
Close this issue for now. this issue can be recreated if there are plans to implement this in the future.
