### ISSUE TITLE
Tiffcreator TIF support

### ISSUE THREAD

**Issue by leuat** [Neural-Systems-at-UIO/nutil#6]

**Comment by leuat** [comment]
Create tiled tiff files from regular tiff files

**Comment by Majpuc** [comment]
@leuat Do you consider this done ?

**Comment by GxHam** [comment]
Hi, I am interested in this as well. Is there a version where this has been implemented? I have tiled tiff files that were processed for shading correction in R and restitched into a single tiff, but I am unable to run any of the modes on it. Would be great if I can convert the single tiff back into tiled tiff using the Tiffcreator.

**Comment by leuat** [comment]
Ok, implemented! Will be included in the next release =)

**Comment by leuat** [comment]
@sharoncy will you able to test this on your system this week? Might happen that Qt needs an upgrade for this to work properly...

**Comment by sharoncy** [comment]
I have tested this feature and it works great. The quick start guide in the GUI and the user manual should be updated.

**Comment by sharoncy** [comment]
The quick start guide and user manual have been updated.
