### ISSUE TITLE
Multiple custom masks

### ISSUE THREAD

**Issue by ingvildeb** [Neural-Systems-at-UIO/nutil#93]
It would be nice to be able to run quantifier with multiple custom masks, separated by RGB color code. I have put a test section with a mask section with multiple regions in different colors here:

Z:\HBP_Analytics\Nutil_Quantifier\Bjerke_normal_material\Multiple_masks_test

**Comment by sharoncy** [comment]
@ingvildeb. I only noticed this request today. Is this something you still need? How important is it for your project? In the future, please assign issues to leuat, sharoncy and Majpuc (see panel in top right), so that we get a notification of the issue.

**Comment by ingvildeb** [comment]
Not important for my project now. I think it would be a good feature if we will keep the custom masks in the future. I did not know I had to assign people, will make sure to do that in the future.

**Comment by sharoncy** [comment]
We do not plan to implement this feature due to other priorities and limited capacity. Open a new issue if this is still needed. 25.08.21.
