### ISSUE TITLE
Template multiplication - recipe for extending a simple case to duplicate .nut files to multiple files

### ISSUE THREAD

**Issue by leuat** [Neural-Systems-at-UIO/nutil#98]

**Comment by Majpuc** [comment]
@leuat Do we have something I can test?

**Comment by leuat** [comment]
This is actually partly implemented, but we lack a GUI system. This is not a priority now.

**Comment by sharoncy** [comment]
Brianna uses a cmd script for making multiple nut files. She can potentially share it as part of the BRAINSPACE project.

**Comment by sharoncy** [comment]
Close for now. 31.05.22.
